sudo: false
language: android
jdk:
  - oraclejdk8

android:
    components:
      - tools
      - build-tools-27.0.3
      - android-25
      - extra-android-m2repository
      - extra-android-support
      - extra

before_script:
  - chmod +x gradlew

script:
    - ./gradlew assembleRelease

